[workspace]
members = [
    # beginner tutorials
    "code/beginner/*",

    # intermediate tutorials
    "code/intermediate/*",

    # showcase
    "code/showcase/*",

    # research
    "code/research/*",
]