[package]
name = "gifs"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
shaderc = "0.6"
cgmath = "0.17.0"
failure = "0.1"
wgpu = "0.5"
futures = "0.3"
gif = "0.10.3"

framework = { path = "../framework" }